export enum SriEnv {
    TEST = '1',
    PRODUCTION = '2',
}

export enum VoucherStatus {
    ERROR = 'ERROR',
    INITIAL = 'INITIAL',
    GENERATED = 'GENERATED',
    SIGNED = 'SIGNED',
    RECEIVED = 'RECEIVED',
    PROCESSING = 'PROCESSING',
    REJECTED = 'REJECTED',
    AUTHORIZED = 'AUTHORIZED',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED'
}